apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-crashloop-helm.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.nginx.config | quote }}
