# This rule is not used by the project kubernaut itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to remediationorchestrator.kubernaut.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/managed-by: kustomize
  name: remediationorchestrator-remediationorchestrator-viewer-role
rules:
- apiGroups:
  - remediationorchestrator.kubernaut.ai
  resources:
  - remediationorchestrators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - remediationorchestrator.kubernaut.ai
  resources:
  - remediationorchestrators/status
  verbs:
  - get
