apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubernaut-system

resources:
  - 01-rbac.yaml
  - 02-configmap.yaml
  - 03-deployment.yaml
  - 04-service.yaml
  - 06-servicemonitor.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kubernaut
      app.kubernetes.io/component: gateway
      app.kubernetes.io/part-of: kubernaut

images:
  - name: quay.io/jordigilh/kubernaut-gateway
    newTag: v0.1.0

