## Append samples of your project ##
resources:
- remediation_v1alpha1_remediationrequest.yaml
- signalprocessing_v1alpha1_signalprocessing.yaml
- aianalysis_v1alpha1_aianalysis.yaml
- workflowexecution_v1alpha1_workflowexecution.yaml
- remediationorchestrator_v1alpha1_remediationorchestrator.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
