---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubernaut-system

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: kubernaut

resources:
  - 01-namespace.yaml
  - 02-serviceaccount.yaml
  - 03-rbac.yaml
  - 04-secret.yaml
  - 05-configmap.yaml
  - 06-deployment.yaml
  - 07-service.yaml
  - 08-networkpolicy.yaml
  - 09-buildconfig.yaml
  - 10-servicemonitor.yaml
  - 11-grafana-dashboard-configmap.yaml
  - 12-prometheus-rules.yaml
  - 13-oauth-proxy-secret.yaml

images:
  - name: holmesgpt-api
    newName: quay.io/jordigilh/kubernaut-holmesgpt-api
    newTag: v1.0.4-amd64

