apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: demo-slo
  labels:
    app: api-gateway
data:
  default.conf: |
    server {
      listen 80;
      location /api/ {
        return 200 '{"status": "ok"}';
        add_header Content-Type application/json;
      }
      location /healthz {
        return 200 "ok";
      }
    }
